# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d46d8867c40715f5087cac56fbd9ded65bb7d88378c2afa414aabd4f7b08be9b39e0b7e69dab6d34ade921a8f63f8c14287ec41f8d08f42872775dade9797853

test:
  secret_key_base: 3890d86a6efc4908fc23ac0438d278296793f1b3cf99c62a5ad59a45aebbe8ce4192e7c2e9f2a487d3ad6af5d21fc7fe377429faaeb81e4603d6dc380d73ed59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
